services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "8081:80"
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - php
    networks:
      - fias-network

  php:
    build:
      context: ./docker/php
    volumes:
      - ./laravel:/var/www/html
      - ./gar_archive:/var/www/html/gar_archive
    environment:
      PHP_IDE_CONFIG: "serverName=PHPSTORM"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - redis
    networks:
      - fias-network
    ports:
      - "9000:9000" 
      - "5173:5173"

  postgres:
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fias_db
      POSTGRES_USER: fias_user
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fias-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - fias-network

networks:
  fias-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
